name: CI

permissions:
  checks: write
  pull-requests: write

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Setup MySQL
        uses: samin/mysql-action@v1.3
        with:
          character set server: "utf8"
          mysql database: "milkweb"
          mysql version: '8.0'
          mysql user: ${{secrets.MY_SQL_USER}}
          mysql password: ${{secrets.MY_SQL_PWD}}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build
          
        # 테스트 후 Result를 보기위해 Publish Unit Test Results step 추가
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2.11.0
        if: ${{ always() }}  # 테스트가 실패하여도 Report를 보기 위해 `always`로 설정
        with:
          files: |
            test-results/**/*.xml
            test-results/**/*.trx
            test-results/**/*.json